// <auto-generated />
using System;
using MediaBoomFileService.Infrastructure.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MediaBoomFileService.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(FileServiceDbContext))]
    [Migration("20260820110358_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MediaBoomFileService.Domain.Entities.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("asset_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<DateTime?>("ReadyAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ready_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("media_assets", "files");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("MediaBoomFileService.Domain.MediaProcessing.AudioProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AudioAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("audio_asset_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<bool>("IsCriticalError")
                        .HasColumnType("boolean")
                        .HasColumnName("is_critical_error");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("integer")
                        .HasColumnName("max_retries");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_retry_at");

                    b.Property<int>("ProgressPercentage")
                        .HasColumnType("integer")
                        .HasColumnName("progress_percentage");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("AudioAssetId");

                    b.ToTable("audio_processes", "files");
                });

            modelBuilder.Entity("MediaBoomFileService.Domain.Entities.AudioAsset", b =>
                {
                    b.HasBaseType("MediaBoomFileService.Domain.Entities.MediaAsset");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<string>("SourceCodec")
                        .HasColumnType("text")
                        .HasColumnName("source_codec");

                    b.Property<string>("SourceContainer")
                        .HasColumnType("text")
                        .HasColumnName("source_container");

                    b.ToTable("audio_assets", "files");
                });

            modelBuilder.Entity("MediaBoomFileService.Domain.Entities.MediaAsset", b =>
                {
                    b.OwnsOne("MediaBoomFileService.Domain.ValueObjects.StorageKey", "SourceObjectKey", b1 =>
                        {
                            b1.Property<Guid>("MediaAssetId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Bucket")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("source_object_key_bucket");

                            b1.Property<string>("FullPath")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("source_object_key_full_path");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("source_object_key_key");

                            b1.Property<string>("Prefix")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("source_object_key_prefix");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("source_object_key_value");

                            b1.HasKey("MediaAssetId");

                            b1.ToTable("media_assets", "files");

                            b1.WithOwner()
                                .HasForeignKey("MediaAssetId");
                        });

                    b.OwnsOne("MediaBoomFileService.Domain.ValueObjects.MediaData", "MediaData", b1 =>
                        {
                            b1.Property<Guid>("MediaAssetId")
                                .HasColumnType("uuid");

                            b1.Property<int>("ExpectedChunksCount")
                                .HasColumnType("integer")
                                .HasColumnName("expected_chunks_count");

                            b1.Property<long>("SizeBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("source_size_bytes");

                            b1.HasKey("MediaAssetId");

                            b1.ToTable("media_assets", "files");

                            b1.WithOwner()
                                .HasForeignKey("MediaAssetId");

                            b1.OwnsOne("MediaBoomFileService.Domain.ValueObjects.ContentType", "ContentType", b2 =>
                                {
                                    b2.Property<Guid>("MediaDataMediaAssetId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Category")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("source_media_type");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("source_content_type");

                                    b2.HasKey("MediaDataMediaAssetId");

                                    b2.ToTable("media_assets", "files");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaDataMediaAssetId");
                                });

                            b1.OwnsOne("MediaBoomFileService.Domain.ValueObjects.FileName", "FileName", b2 =>
                                {
                                    b2.Property<Guid>("MediaDataMediaAssetId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Extension")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("source_file_extension");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("source_file_name");

                                    b2.HasKey("MediaDataMediaAssetId");

                                    b2.ToTable("media_assets", "files");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaDataMediaAssetId");
                                });

                            b1.Navigation("ContentType")
                                .IsRequired();

                            b1.Navigation("FileName")
                                .IsRequired();
                        });

                    b.Navigation("MediaData")
                        .IsRequired();

                    b.Navigation("SourceObjectKey");
                });

            modelBuilder.Entity("MediaBoomFileService.Domain.MediaProcessing.AudioProcess", b =>
                {
                    b.HasOne("MediaBoomFileService.Domain.Entities.AudioAsset", null)
                        .WithMany()
                        .HasForeignKey("AudioAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("MediaBoomFileService.Domain.MediaProcessing.ProcessingStep", "Steps", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("AudioProcessId")
                                .HasColumnType("uuid")
                                .HasColumnName("audio_process_id");

                            b1.Property<DateTime?>("CompletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("completed_at");

                            b1.Property<string>("ErrorMessage")
                                .HasColumnType("text")
                                .HasColumnName("error_message");

                            b1.Property<int>("Order")
                                .HasColumnType("integer")
                                .HasColumnName("order");

                            b1.Property<string>("ResultData")
                                .HasColumnType("jsonb")
                                .HasColumnName("result_data");

                            b1.Property<DateTime?>("StartedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("started_at");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("status");

                            b1.Property<string>("StepType")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("step_type");

                            b1.Property<int>("Weight")
                                .HasColumnType("integer")
                                .HasColumnName("weight");

                            b1.HasKey("Id");

                            b1.HasIndex("AudioProcessId")
                                .HasDatabaseName("ix_processing_steps_audio_process_id");

                            b1.HasIndex("Status")
                                .HasDatabaseName("ix_processing_steps_status");

                            b1.HasIndex("StepType")
                                .HasDatabaseName("ix_processing_steps_step_type");

                            b1.ToTable("processing_steps", "files");

                            b1.WithOwner()
                                .HasForeignKey("AudioProcessId");
                        });

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("MediaBoomFileService.Domain.Entities.AudioAsset", b =>
                {
                    b.HasOne("MediaBoomFileService.Domain.Entities.MediaAsset", null)
                        .WithOne()
                        .HasForeignKey("MediaBoomFileService.Domain.Entities.AudioAsset", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MediaBoomFileService.Domain.ValueObjects.StorageKey", "HlsManifestObjectKey", b1 =>
                        {
                            b1.Property<Guid>("AudioAssetId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Bucket")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("hls_manifest_object_key_bucket");

                            b1.Property<string>("FullPath")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("hls_manifest_object_key_full_path");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("hls_manifest_object_key_key");

                            b1.Property<string>("Prefix")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("hls_manifest_object_key_prefix");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("hls_manifest_object_key_value");

                            b1.HasKey("AudioAssetId");

                            b1.ToTable("audio_assets", "files");

                            b1.WithOwner()
                                .HasForeignKey("AudioAssetId");
                        });

                    b.Navigation("HlsManifestObjectKey");
                });
#pragma warning restore 612, 618
        }
    }
}
